task:
  task_name: ForecastOPF
data:
  baseMVA: 100
  mask_value: 0.0
  normalization: HeteroDataMVANormalizer
  networks:
  - case14_ieee
  scenarios:
  - 26280 #3yrs
  test_ratio: 0.15
  val_ratio: 0.15
  workers: 32
  split_by_load_scenario_idx: true
  temporal_split: true  
model:
  attention_head: 8
  edge_dim: 10
  hidden_size: 48
  input_bus_dim: 15
  input_gen_dim: 6
  output_bus_dim: 5 # P_d, Q_d, V_m, V_a, Q_g
  output_gen_dim: 1
  num_layers: 12
  type: GNS_heterogeneous
optimizer:
  beta1: 0.9
  beta2: 0.999
  learning_rate: 0.0005
  lr_decay: 0.7
  lr_patience: 5
training:
  batch_size: 64
  epochs: 200
  loss_weights:
  - 0.3
  - 0.3
  - 0.4
  losses:
  - LayeredWeightedPhysics
  - MaskedGenMSE
  - MaskedBusMSE
  loss_args:
  - base_weight: 0.5
  - {}
  - {}
  accelerator: auto
  devices: auto
  strategy: auto
seed: 0
verbose: true
callbacks:
  patience: 100
  tol: 0
